### ISSUE TITLE
Not compiling on Asterisk 13.8-cert4

### ISSUE THREAD

**Issue by lpradovera** [unispeech/asterisk-unimrcp#16]
Hello,
I am getting the following errors with compiling on Asterisk 13.8-cert4: https://gist.github.com/lpradovera/9bf1be1889e94d02fb67aef8f97edcc4

I installed UniMRCP and the deps from a Git checkout, and the Asterisk module is from Github too.
I would be happy to help debug and resolve this but I have no idea of where to start from.
Thanks!

**Comment by achaloyan** [comment]
Hello Luca,

Could you provide ./configure output. I am curious whether Asterisk version is properly determined.

**Comment by lpradovera** [comment]
Hello @achaloyan !
Here it is, it does look like it is reporting correctly but let me know what your thoughts are: https://gist.github.com/lpradovera/4e9af5688d1931479ed84056253238a1

**Comment by achaloyan** [comment]
The problem is the version is supposed to be in a major.minor[.patch] form; otherwise version dependent normalization badly fails.

Explicitly specify the version number as an input parameter:
./configure --with-asterisk-version=13.8.4

or enhance the version detection [asterisk.m4](https://github.com/unispeech/asterisk-unimrcp/blob/master/build/acmacros/asterisk.m4) macro to take into consideration the "certified" prefix.
